// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalDiary.Persistence;

#nullable disable

namespace PersonalDiary.Persistence.Migrations
{
    [DbContext(typeof(DiaryDbContext))]
    [Migration("20250119194046_AddFoodPlaceReviewEntity")]
    partial class AddFoodPlaceReviewEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonalDiary.Domain.Models.Dictionaries.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.ToTable("cities");
                });

            modelBuilder.Entity("PersonalDiary.Domain.Models.FoodPlaces.FoodPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_id");

                    b.Property<int>("Cousine")
                        .HasColumnType("integer")
                        .HasColumnName("cousine");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("ReviewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("review_count");

                    b.Property<float>("ReviewValue")
                        .HasColumnType("real")
                        .HasColumnName("review_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_food_places");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_food_places_city_id");

                    b.ToTable("food_places");
                });

            modelBuilder.Entity("PersonalDiary.Domain.Models.MyTask.MyTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeadLine")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dead_line");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("BoardId")
                        .HasDatabaseName("ix_tasks_board_id");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("PersonalDiary.Domain.Models.MyTask.TaskBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_task_boards");

                    b.ToTable("task_boards");
                });

            modelBuilder.Entity("PersonalDiary.Domain.Models.Reviews.FoodPlaceReview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("FoodPlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("food_place_id");

                    b.Property<byte>("FoodRating")
                        .HasColumnType("smallint")
                        .HasColumnName("food_rating");

                    b.Property<float>("Rating")
                        .HasColumnType("real")
                        .HasColumnName("rating");

                    b.Property<byte>("ServiceRating")
                        .HasColumnType("smallint")
                        .HasColumnName("service_rating");

                    b.Property<byte>("VibeRating")
                        .HasColumnType("smallint")
                        .HasColumnName("vibe_rating");

                    b.HasKey("Id")
                        .HasName("pk_food_place_reviews");

                    b.HasIndex("FoodPlaceId")
                        .HasDatabaseName("ix_food_place_reviews_food_place_id");

                    b.ToTable("food_place_reviews");
                });

            modelBuilder.Entity("PersonalDiary.Domain.Models.FoodPlaces.FoodPlace", b =>
                {
                    b.HasOne("PersonalDiary.Domain.Models.Dictionaries.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_food_places_cities_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("PersonalDiary.Domain.Models.MyTask.MyTask", b =>
                {
                    b.HasOne("PersonalDiary.Domain.Models.MyTask.TaskBoard", "Board")
                        .WithMany("Tasks")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_task_boards_board_id");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("PersonalDiary.Domain.Models.Reviews.FoodPlaceReview", b =>
                {
                    b.HasOne("PersonalDiary.Domain.Models.FoodPlaces.FoodPlace", "FoodPlace")
                        .WithMany()
                        .HasForeignKey("FoodPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_food_place_reviews_food_places_food_place_id");

                    b.Navigation("FoodPlace");
                });

            modelBuilder.Entity("PersonalDiary.Domain.Models.MyTask.TaskBoard", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
